name: Docker Image CI

on:
  push:
    branches: ["deploy"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t daily-alley:latest --load .

      - name: Save Docker image as tar
        run: docker save -o daily-alley.tar daily-alley:latest

      - name: Copy Docker image to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "daily-alley.tar"
          target: "/home/ec2-user/ai"

      - name: Load Docker image and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop daily-alley-container || true
            docker rm daily-alley-container || true
            docker rmi daily-alley:latest || true
            docker load -i /home/ec2-user/ai/daily-alley.tar
            docker run -d --name daily-alley-container -p 8000:8000 \
              -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
              -e GEMINI_MODEL=${{ secrets.GEMINI_MODEL }} \
              daily-alley:latest
            docker exec daily-alley-container sh -c "uvicorn routes:app --host 0.0.0.0 --port 8000 --reload &"
